### ISSUE TITLE
Triangle on dropdown left behind with popup

### ISSUE THREAD

**Issue by gm7** [GrindrodBank/spoon-ui#3]
**Describe the bug**
When the dropdown button is clicked and the "dropdown" pops up, then the little triangle is left behind (underneath) when dropdown pops over. Also the dropdown appears under the bar at the top of the screen.

**To Reproduce**
1. Go to 'https://grindrodbank.github.io/spoon-ui/#/dropdowns'
2. Click on 'Multiple, overflow with search'
3. See error

**Expected behavior**
The dropdown should appear 'connected' to the control, the little triangle should not be left behind and the "dropdown" window should not appear underneath the title bar at the top of the page.

**Screenshots**
![Spoon-ui bug](https://user-images.githubusercontent.com/1935321/59346069-c0326780-8d11-11e9-88a5-5fe37b4f2772.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser firefox
 - Version Quantum 67.0.1 (64-bit)
Also reproduced in Chromium - Version 74.0.3729.169 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)

**Smartphone (please complete the following information):**
n/a

**Comment by mvniekerk** [comment]
Hello @gm7 
Thank you for submitting. A fix has been committed with PR https://github.com/GrindrodBank/spoon-ui/pull/8 
You can follow the progress there as well.
