### ISSUE TITLE
Address SNYK-JS-HANDLEBARS-174183

### ISSUE THREAD

**Issue by gm7** [GrindrodBank/spoon-ui#5]
**Describe the bug**
Address the security risk [SNYK-JS-HANDLEBARS-174183](https://snyk.io/vuln/SNYK-JS-HANDLEBARS-174183)

**To Reproduce**
n/a

**Expected behavior**
Security vulnerabilities to be patched as soon as identified.

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
Still an issue with the latest version of handlebars. Can we use another library?

**Comment by mvniekerk** [comment]
Thank you @gm7 for reporting this
A fix has been committed : https://github.com/GrindrodBank/spoon-ui/pull/10
